version: '2'
services:
    apache:
        build:
            context: ./apache
        image: php:7.2.1-apache
        restart: always
        ports:
            - 80:80
        volumes:
            - ./www:/var/www:z
        links:
            - 'mariadb'

    mariadb:
        image: mariadb:10.1
        restart: always
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/Warsaw"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - 3306:3306

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    mariadb:
